from __future__ import annotations

from typing import Protocol


class Cache(Protocol):
    """Abstract cache -- swap Redis/Memcached/in-memory."""

    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def ping(self) -> bool: ...
